### ISSUE TITLE
get/update in parent containing a value retrieved from key

### ISSUE THREAD

**Issue by awesomo4000** [freywaid/dotted#2]
Great library - just what I needed .. also -

I have a need to access the parent container for a value obtained via `dotted.get` or `dotted.pluck`, then to add or update values in the parent. Would you consider adding something like this to the api ?

One problem I ran into was that parsing a key caches it, and for some reason copy.deepcopy of Dotted objects raised an exception. Hence, the lru cache clear on dotted.api._parse.

This currently works to update the parent of a key, but probably has mysterious edge cases:

```python
import dotted

def get_parent_key(key: str):
    parsed = dotted.parse(key)
    parsed.ops = parsed.ops[:-1]
    parent_key = parsed.assemble()
    # modifying parsed key makes subsequent lookups fail because of cache, so clear the cache
    dotted.api._parse.cache_clear()
    return parent_key


def get_parent(obj, key):
    return dotted.get(obj, get_parent_key(key))


def update_parent(obj, key, update):
    parent_key = get_parent_key(key)
    res = dotted.update(obj, parent_key, update)
    return dotted.get(res, parent_key)

```

Example usage:

```python
>>> import dotted
>>> obj = { 'P' : [ { 'C' : 1 } ] }
>>> res = update_parent(obj, "P[0].C",{ 'C' : 999, 'D' : 2 })
>>> print(res)
{'C': 999, 'D': 2}
>>> res = dotted.get(obj, "P[0].C")
>>> print(res)
999
>>> res = dotted.get(obj, "P[0].D")
>>> print(res)
2
```

**Comment by freywaid** [comment]
Hi,

Interesting problem.  To understand, the general problem is that you'd like to drop the last op in a parsed dotted string, and you'd like to not care about the contents of that string, correct?  For example, you couldn't simply do:

```
>>> import dotted
>>> obj = { 'P' : [ { 'C' : 1 } ] }
>>> dotted.update(obj, 'P[0]', { 'C' : 999, 'D' : 2 })
{'P': [{'C': 999, 'D': 2}]}
```

If so, I think it'd be better to introduce a `disassemble` API to produce the deconstructed ops as strings to be called by the `api.assemble` func.  I can add that.  Something like:

```
>>> import dotted
>>> key = dotted.assemble(dotted.disassemble('P[0].C')[:-1])
>>> dotted.update(obj, key, value)
```

**Comment by freywaid** [comment]
Now that I look at this some more, I realized I don't need disassemble at all... You should be able to do this with parse/assemble.  But there's a bug.  Latest should make it so `assemble` can consume pre-parsed dotted strings.

**Comment by awesomo4000** [comment]
Thanks a bunch. This ended up working for me, shortening my code, and avoiding the issue I had from modifying the .ops attribute of the cached pre-parsed item.

This is what the above turned into:

```python

def get_parent_key(key):
    return dotted.assemble(dotted.parse(key)[:-1])


def get_parent(obj, key):
    return dotted.get(obj, get_parent_key(key))


def update_parent(obj, key, val):
    parent_key = get_parent_key(key)
    res = dotted.update(obj, parent_key, val)
    return dotted.get(res, parent_key)

```

Cheers.

**Comment by freywaid** [comment]
Cool.  Glad it worked out.  Nice to see someone using this package :).
