### ISSUE TITLE
pattern delimiters lost when assembling parsed key

### ISSUE THREAD

**Issue by awesomo4000** [freywaid/dotted#4]
When assembling a parsed key, the pattern delimiters are lost:

```python
>>> dotted.assemble(dotted.parse("/A.+/"))
>>> 'A.+'
```

Perhaps I'm misunderstanding, but IMO assemble should return the same key that was fed to parse.

**Comment by freywaid** [comment]
It should.  Let me take a look.

**Comment by freywaid** [comment]
Pushed 0.8.8.  Should fix your issue.  Let me know.  And keep the bugs coming!

**Comment by awesomo4000** [comment]
Works. thanks!
