### ISSUE TITLE
Feature request: Search by dict value

### ISSUE THREAD

**Issue by brihuega** [freywaid/dotted#5]
First of all, big thanks for this great utility. It's very useful to me.
It would be great if it could find by values in dictionaries. In my project, I have a lot of data structures in the form of key-values, so it will be useful to match them automatically with dotted.

For instance:
<pre>
    data = {
        'myclients': [
            {'id': 1, 'name': 'John'},
            {'id': 2, 'name': 'David'},
            {'id': 3, 'name': 'Anne'},
        ]
    }
   myid = dotted.get(data, 'myclients[name="David"].id')
</pre>
Desired result: myid = 2

Many thanks in advance.
Jose

**Comment by freywaid** [comment]
Hi Jose,

I'm thinking about this proposal.  Let me try some things.

Frey

**Comment by freywaid** [comment]
Try latest release.  I think I got it working.  Lemme know if you see any bugs; there surely will be.

**Comment by brihuega** [comment]
Thank you very much, Frey, for the quick response.
The filters seem to work great, but bracketed indexing and slicing don't work over filtered lists.

(tested on Python 3.8.10):
<pre>
data={'clients': [{'name':'John', 'city':'London'}, {'name':'David', 'city':'Paris'}, {'name':'Anne', 'city':'London'}]}
dotted.get(data, 'clients[1:]')    # OK
[{'name': 'David', 'city': 'Paris'}, {'name': 'Anne', 'city': 'London'}]
dotted.get(data, 'clients[city="London"]')  # OK
({'name': 'John', 'city': 'London'}, {'name': 'Anne', 'city': 'London'})
dotted.get(data, 'clients[city="London"][0]')   # Fail!
()
dotted.get(data, 'clients[city="London"][1:]')   # Fail!
()
</pre>

**Comment by freywaid** [comment]
Unfortunately, I tried to get both styles working together: slicing and
bracketing. There's an ambiguity. I'll think about it further and may come
up with something.

**Comment by brihuega** [comment]
I understand it. Thank you for your efforts. It's a challenge to put all those features together.

In future releases it also could be combined with the match-first operator. For instance,  'clients[city="London"?]' to return the first item that matches.

Best regards

**Comment by freywaid** [comment]
OK.  Fixed.  The `[key=value]` filter acts on slices and not on items.  The
grammar was corrected and now does what you'd expect.  I jettisoned the
sol'n where I created an ambiguity so this is correct going forward.

Let me know.

Frey

**Comment by brihuega** [comment]
Wow! It's perfect for me!
Many thanks for your kind and quick help.

**Comment by freywaid** [comment]
key-value first added with latest
